version: "3.9"

services:
  
  api:
    build:
      context: ./api
      target: caricare-api-dev # only use the dev step
    container_name: caricare-api
    image: caricare-api
    init: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    networks:
      - caricare
    environment:
      - PG_CONNECTION_STRING=postgresql://postgres:password@db:5432/caricare

  app:
    build:
      context: ./app
      target: caricare-app-dev # only use the dev step
    container_name: caricare-app
    image: caricare-app
    init: true
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./app:/app
    networks:
      - caricare

  db:
    build:
      context: ./db
    container_name: caricare-db
    image: caricare-db
    networks:
      - caricare
    command: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password

networks:
  caricare:
    name: caricare

volumes:
  postgres-data:
