ARG NODE_VERSION=18
ARG DEBIAN_FRONTEND=noninteractive

FROM node:${NODE_VERSION} as builder

WORKDIR /app

COPY .  ./

RUN npm install
RUN npm run build


# ---- PROD IMAGE SERVING JS
FROM nginx:1.25.3-alpine as caricare-app-prod
ENV NODE_ENV=production
COPY --from=builder /app/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


CMD ["nginx", "-g", "daemon off;"]