ARG NODE_VERSION=18
ARG DEBIAN_FRONTEND=noninteractive

FROM node:${NODE_VERSION} as caricare-api-base

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json


# -- DEV
FROM caricare-api-base as caricare-api-dev
ENV NODE_ENV=development

RUN apt-get update && apt-get install --no-install-recommends -y

# Dependencies are volume mounted in the container
ENTRYPOINT [ "./init.sh" ]

# -- TEST
FROM caricare-api-base as caricare-api-tests
ENV NODE_ENV=test

RUN apt-get update && apt-get install --no-install-recommends -y


ENTRYPOINT [ "./init-test.sh" ]

